/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GameBuilderRouteImport } from './routes/GameBuilder'
import { Route as ChangelogRouteImport } from './routes/Changelog'
import { Route as IndexRouteImport } from './routes/index'

const GameBuilderRoute = GameBuilderRouteImport.update({
  id: '/GameBuilder',
  path: '/GameBuilder',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/Changelog',
  path: '/Changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Changelog': typeof ChangelogRoute
  '/GameBuilder': typeof GameBuilderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Changelog': typeof ChangelogRoute
  '/GameBuilder': typeof GameBuilderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Changelog': typeof ChangelogRoute
  '/GameBuilder': typeof GameBuilderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Changelog' | '/GameBuilder'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Changelog' | '/GameBuilder'
  id: '__root__' | '/' | '/Changelog' | '/GameBuilder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  GameBuilderRoute: typeof GameBuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/GameBuilder': {
      id: '/GameBuilder'
      path: '/GameBuilder'
      fullPath: '/GameBuilder'
      preLoaderRoute: typeof GameBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Changelog': {
      id: '/Changelog'
      path: '/Changelog'
      fullPath: '/Changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  GameBuilderRoute: GameBuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
